version: '2.3'
services:
  database:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim
    environment:
      - POSTGRES_USER=openapparelregistry
      - POSTGRES_PASSWORD=openapparelregistry
      - POSTGRES_DB=openapparelregistry
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "openapparelregistry"]
      interval: 3s
      timeout: 3s
      retries: 3

  django:
    image: "openapparelregistry:${GIT_COMMIT:-latest}"

  terraform:
    image: quay.io/azavea/terraform:0.11.11
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-open-apparel-registry}
      - GIT_COMMIT=${GIT_COMMIT:-latest}
      - OAR_DEBUG=1
      - OAR_SETTINGS_BUCKET=openapparelregistry-staging-config-us-east-1
    working_dir: /usr/local/src
    entrypoint: bash
