---
- name: Set AWS_PROFILE
  lineinfile: 
    path: "/etc/environment" 
    regexp: "^AWS_PROFILE="
    line: "AWS_PROFILE={{ aws_profile }}"

- name: Set vm.max_map_count for ElasticSearch
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
